# Generated by Django 3.2.3 on 2021-09-02 15:19

import accounts.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('accounts', '0002_auto_20210902_1439'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, default=None, max_length=12, null=True,
                                   validators=[accounts.validators.validate_is_digits]),
        ),
    ]
