# Generated by Django 3.2.3 on 2021-07-16 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currency_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analytics',
            name='status_code',
            field=models.CharField(default=0, max_length=3),
        ),
    ]
