# Generated by Django 3.2.3 on 2021-07-16 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currency_app', '0002_alter_analytics_status_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analytics',
            name='status_code',
            field=models.CharField(max_length=3),
        ),
        migrations.AlterField(
            model_name='rate',
            name='moneytype',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Dollar'), (1, 'Euro')]),
        ),
    ]
