# Generated by Django 3.2.3 on 2021-07-20 14:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('currency_app', '0003_auto_20210716_0815'),
    ]

    operations = [
        migrations.AddField(
            model_name='bank',
            name='origin_url',
            field=models.URLField(default='www.google.com'),
        ),
        migrations.AddField(
            model_name='rate',
            name='bank',
            field=models.ForeignKey(default=None, null=True,
                                    on_delete=django.db.models.deletion.CASCADE,
                                    to='currency_app.bank'),
        ),
        migrations.AlterField(
            model_name='bank',
            name='name',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='bank',
            name='url',
            field=models.URLField(),
        ),
    ]
