# Generated by Django 3.2.3 on 2021-07-20 17:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('currency_app', '0006_auto_20210720_1705'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rate',
            name='bank',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='currency_app.bank'),
        ),
    ]
