# Generated by Django 3.2.3 on 2021-07-20 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currency_app', '0008_bank_code_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bank',
            name='code_name',
            field=models.CharField(max_length=64, unique=True),
        ),
        migrations.AlterField(
            model_name='bank',
            name='origin_url',
            field=models.URLField(),
        ),
    ]
