# Generated by Django 3.2.3 on 2021-07-20 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('currency_app', '0009_auto_20210720_1732'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rate',
            name='source',
        ),
    ]
