# Generated by Django 3.2.3 on 2021-07-20 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currency_app', '0010_remove_rate_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='rate',
            name='source',
            field=models.CharField(default='assd', max_length=64),
        ),
    ]
