# Generated by Django 3.2.3 on 2021-07-20 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('currency_app', '0011_rate_source'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rate',
            name='source',
        ),
    ]
